spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          isolation: '2'
        default_schema: spring_boot_starter_security_boot
        format_sql: 'true'
        generate_statistics: 'true'
        hbm2ddl:
          auto: update
        jdbc:
          batch_size: '5'
          fetch_size: '5'
        packagesToScan: idv.hsiehpinghan.springbootstartersecurityboot.**.entity
        show_sql: 'true'
        use_sql_comments: 'true'
  datasource:
    password: '!)09w5t43w1oJ'
    url: jdbc:postgresql://localhost:5432/postgres
    username: thank
  thymeleaf:
    mode: LEGACYHTML5
logging:
  level:
    idv.hsiehpinghan: INFO
    root: INFO