spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        connection:
          isolation: '2'
        default_schema: spring_boot_starter_security_boot
        format_sql: 'true'
        generate_statistics: 'true'
        hbm2ddl:
          auto: update
        jdbc:
          batch_size: '5'
          fetch_size: '5'
        packagesToScan: idv.hsiehpinghan.springbootstartersecurityboot.**.entity
        show_sql: 'true'
        use_sql_comments: 'true'
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    password: ''
    url: jdbc:h2:file:/tmp/h2
    username: sa
  thymeleaf:
    mode: LEGACYHTML5
logging:
  level:
    idv.hsiehpinghan: INFO
    root: INFO