spring:
  postgresqldatasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=spring_boot_starter_data_jpa_boot
    username: thank
    password: '!)09w5t43w1oJ'
  mysqldatasource:
    url: jdbc:mysql://localhost:3306/spring_boot_starter_data_jpa_boot
    username: thank
    password: '%j6w1oW'
  postgresqljpa:
    open-in-view: false
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow
        connection:
          isolation: '2'
        format_sql: 'true'
        generate_statistics: 'true'
        hbm2ddl:
          auto: update
        jdbc:
          batch_size: '5'
          fetch_size: '5'
          lob:
            non_contextual_creation: true
        packagesToScan: idv.hsiehpinghan.springbootstarterdatajpaboot.**.entity.postgresql
        show_sql: 'true'
        use_sql_comments: 'true'
        globally_quoted_identifiers: 'true'
  mysqljpa:
    open-in-view: false
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow
        connection:
          isolation: '2'
        format_sql: 'true'
        generate_statistics: 'true'
        hbm2ddl:
          auto: update
        jdbc:
          batch_size: '5'
          fetch_size: '5'
          lob:
            non_contextual_creation: true
        packagesToScan: idv.hsiehpinghan.springbootstarterdatajpaboot.**.entity.mysql
        show_sql: 'true'
        use_sql_comments: 'true'
        globally_quoted_identifiers: 'true'
logging:
  level:
    idv.hsiehpinghan: INFO
    root: INFO