configuration:
  property: configuration_property
endpoints:
  shutdown:
    enabled: 'true'
info:
  build:
    artifact: '@project.artifactId@'
    description: '@project.description@'
    name: '@project.name@'
    version: '@project.version@'
management:
  address: 127.0.0.1
  context-path: /spring_actuator
  port: '8080'
  security:
    enabled: 'true'
    roles: ADMIN
server:
  port: '8080'
spring:
  jpa:
    properties:
      hibernate:
        connection:
          isolation: '2'
        default_schema: spring_boot_starter_web_boot
        format_sql: 'true'
        generate_statistics: 'true'
        hbm2ddl:
          auto: update
        jdbc:
          batch_size: '5'
          fetch_size: '5'
        packagesToScan: idv.hsiehpinghan.springbootstarterwebboot.**.entity
        show_sql: 'true'
        use_sql_comments: 'true'
  thymeleaf:
    mode: LEGACYHTML5
