management:
  security:
    enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
zuul:
  sensitive-headers: Cookie,Set-Cookie
  ignored-services: '*'
  prefix: /api
  routes:
    google:
      path: /google/**
      url: https://www.google.com/
    service:
      path: /service/**
      url: spring-cloud-starter-eureka-boot