server:
  port: 8081
security:
  oauth2:
    resource:
      id: resource_id
auth:
  server:
    url: http://redis-token-store-authorization-server:8080/oauth/check_token/
    clientId: client_id
    clientsecret: client_secret