security:
  oauth2:
    resource:
      id: resource_id
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
        hbm2ddl:
          auto: update
        packagesToScan: idv.hsiehpinghan.springcloudstarteroauth2boot.**.entity
        show_sql: 'true'
        use_sql_comments: 'true'
  redis:
    host: my_redis
    port: 6379
    database: 0
    pool:
      max-active: 8
      max-idle: 8
      max-wait: 0
      min-idle: 0
    timeout: 5000
logging:
  level:
    idv.hsiehpinghan: INFO
    root: INFO