server:
  port: 8763
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 1000