security:
  oauth2:
    resource:
      id: resource_id
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    pool:
      max-active: 8
      max-idle: 8
      max-wait: 0
      min-idle: 0
    timeout: 0
  datasource:
    password: ''
    url: jdbc:h2:file:/tmp/h2
    username: sa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
logging:
  level:
    idv.hsiehpinghan: INFO
    root: INFO