security:
  oauth2:
    resource:
      id: resource_id
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    pool:
      max-active: 8
      max-idle: 8
      max-wait: 0
      min-idle: 0
    timeout: 0
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          isolation: '2'
        default_schema: spring_security_oauth2_boot
        format_sql: 'true'
        generate_statistics: 'true'
        hbm2ddl:
          auto: update
        jdbc:
          batch_size: '5'
          fetch_size: '5'
        packagesToScan: idv.hsiehpinghan.springsecurityoauth2boot.**.entity
        show_sql: 'true'
        use_sql_comments: 'true'
  datasource:
    password: '!)09w5t43w1oJ'
    url: jdbc:postgresql://localhost:5432/postgres
    username: thank
  thymeleaf:
    mode: LEGACYHTML5