server:
  port: 8083
security:
  oauth2:
    resource:
      user-info-uri: http://172.17.0.1:8082/auth/user
auth:
  server:
    url: http://172.17.0.1:8082/oauth/check_token/
    clientId: trusted-app
    clientsecret: secret