server:
  port: '8080'
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hsiehpinghan/boot/tree/master/spring-cloud-config-server-boot/src/test/resources
          search-paths:
          - spring-cloud-config-client-boot