server:
  port: '8080'
spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///home/hsiehpinghan/git/boot/spring-cloud-config-server-boot/src/test/resources/spring-cloud-config-client-boot
  profiles:
    active: native