spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    password: ''
    url: jdbc:h2:mem:spring-boot-starter-web-boot-2
    username: sa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        connection:
          isolation: '2'
        format_sql: 'true'
        generate_statistics: 'true'
        hbm2ddl:
          auto: update
        jdbc:
          batch_size: '5'
          fetch_size: '5'
        packagesToScan: idv.hsiehpinghan.springbootstarterwebboot.**.entity
        show_sql: 'true'
        use_sql_comments: 'true'
  thymeleaf:
    mode: HTML
    
logging:
  level:
    idv.hsiehpinghan: INFO
    root: INFO
